version: 2
registries:
  pnt-mvn:
    type: maven-repository
    url: https://repo.pentaho.com/artifactory/pnt-mvn
    username: ${{ secrets.PENTAHO_CICD_ONE_USER }}
    password: ${{ secrets.PENTAHO_CICD_ONE_KEY }}
    replaces-base: true
updates:
  - package-ecosystem: maven
    directory: /
    registries:
      - pnt-mvn
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    allow:
      - dependency-name: io.netty:*
      - dependency-name: org.pentaho.hadoop:pentaho-shaded-netty
      - dependency-name: org.bouncycastle:*
    ignore:
      - dependency-name: io.netty:*
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.bouncycastle:*
        update-types:
          - version-update:semver-major
