version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: io.netty:*
      - dependency-name: org.bouncycastle:*
    ignore:
      - dependency-name: io.netty:*
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: org.bouncycastle:*
        update-types:
          - version-update:semver-major
